name: Run tests

on:
  push:
    branches:
    - master
    - actions

jobs:
  test-linux:
    name: Run tests (linux)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
  
  rest-macos:
    name: Run tests (macOS)
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose